### ISSUE TITLE
Doesn't sign me in

### ISSUE THREAD

**Issue by eyoba-bisru** [bitcraft3r/bolt-boilerplate-nextjs#3]
I signed up in the boilerplate website then after posting one post I sign out but when I try to sign in it shows an the below error.
<img width="1078" alt="image" src="https://github.com/bitcraft3r/bolt-boilerplate-nextjs/assets/60362517/ad6823da-c154-45a5-941d-92da8d3e7407">

**Comment by bitcraft3r** [comment]
Hey @eyoba-bisru, enabled an Authentication strategy on Clerk and it should work now!

<img width="924" alt="image" src="https://github.com/bitcraft3r/bolt-boilerplate-nextjs/assets/8282076/27eca075-a8b2-4fb3-8cea-1247ee8ca48e">
