### ISSUE TITLE
Switch to pnpm

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [bitcraft3r/bolt-boilerplate-nextjs#5]
I'm using pnpm for all of my projects so to use this boilerplate I would have to switch to pnpm everytime (this is not what I want).

![image](https://github.com/bitcraft3r/bolt-boilerplate-nextjs/assets/77451351/7dc4cfb3-5c36-4a7f-b64e-bc62e9563cb3)

**Comment by bitcraft3r** [comment]
Hey @FleetAdmiralJakob I'm not familiar with pnpm.

What about creating a fork or branch to [implement the necessary migrations](https://britishgeologicalsurvey.github.io/development/migrating-from-npm-to-pnpm/#getting-started) to use pnpm by default with this boilerplate?

**Comment by FleetAdmiralJakob** [comment]
I can't create a branch because you did not set me as a contributor but I can create a fork

**Comment by bitcraft3r** [comment]
very good work @FleetAdmiralJakob ! thanks!
 
i had some trouble adding you as a collaborator on the project.. will check again tomorrow so ideally we can have this on a separate branch.

**Comment by FleetAdmiralJakob** [comment]
Merged into the https://github.com/bitcraft3r/bolt-boilerplate-nextjs/tree/pnpm branch
